name: quinientas_historias
description: 500Historias app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0-beta.2

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  alice_lightweight: ^3.1.0
  async: ^2.10.0
  auto_route: ^6.1.0
  auto_size_text: ^3.0.0
  bloc: ^8.0.3
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.3.2
  cupertino_icons: ^1.0.4
  custom_nested_scroll_view:
    git:
      url: https://github.com/AccentioStudios/custom_nested_scroll_view.git
  dart_jsonwebtoken: ^2.4.1
  device_info_plus: ^8.1.0
  dio: ^5.0.1
  firebase_analytics: ^10.1.1
  firebase_auth: ^4.2.6
  firebase_core: ^2.6.0
  firebase_core_web: ^2.1.1
  firebase_crashlytics: ^3.0.12
  firebase_messaging: ^14.2.2
  firebase_remote_config: ^3.0.10
  firebase_storage: ^11.0.11
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_html: ^3.0.0-alpha.6
  flutter_local_notifications: ^13.0.0
  flutter_math_fork: ^0.6.3+1
  flutter_native_splash: ^2.2.13
  flutter_native_timezone: ^2.0.0
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^1.0.0
  flutter_web_auth: ^0.5.0
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  html_unescape: ^2.0.0
  http: ^0.13.4
  image_cropper: ^3.0.0
  image_picker: ^0.8.6
  infinite_scroll_pagination: ^3.2.0
  introduction_screen: ^3.1.8
  multiselect:
    git:
      url: https://github.com/alvarogabrielgomez/multiselect.git
  openid_client: ^0.4.7
  opentelemetry: ^0.15.1
  package_info_plus: ^3.0.3
  pin_code_fields: ^7.4.0
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.4
  queue: ^3.1.0+2
  rive: ^0.10.1
  rxdart: ^0.27.4
  shared_preferences: ^2.0.15
  skeleton_text: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  timezone: ^0.9.0
  uni_links: ^0.5.1
  universal_html: ^2.0.8
  url_launcher: ^6.0.4
  uuid: ^3.0.6
  webview_flutter: ^4.2.0
  webview_flutter_android: ^3.6.1
  webview_flutter_wkwebview: ^3.4.0

dev_dependencies:
  auto_route_generator: ^6.1.0
  build_runner: ^2.1.11
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
  fonts:
    # - family: Proxima
    #   fonts:
    #     - asset: assets/fonts/ProximaNova/ProximaNova-Regular.otf
    - family: Literata
      fonts:
        - asset: assets/fonts/Literata/Literata-VariableFont.ttf
        - asset: assets/fonts/Literata/Literata-Italic-VariableFont.ttf
          style: italic
