name: quinientas_historias
description: 500Historias app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0-beta.1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  alice_lightweight: ^3.1.0
  auto_size_text: ^3.0.0
  bloc: ^8.0.3
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.4
  custom_nested_scroll_view:
    git:
      url: https://github.com/AccentioStudios/custom_nested_scroll_view.git
  dart_jsonwebtoken: ^2.4.1
  device_info_plus: ^3.2.3
  firebase_analytics: ^9.3.4
  firebase_auth: ^3.3.19
  firebase_core: ^1.24.0
  firebase_core_web: ^1.7.3
  firebase_crashlytics: ^2.8.10
  firebase_messaging: ^13.1.0
  firebase_remote_config: ^2.0.17
  firebase_storage: ^10.3.11
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_html: ^3.0.0-alpha.6
  flutter_local_notifications: ^12.0.2
  flutter_math_fork: ^0.6.3+1
  flutter_native_timezone: ^2.0.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.0
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.0.3
  google_fonts: ^3.0.1
  html_unescape: ^2.0.0
  http: ^0.13.4
  image_cropper: ^3.0.0
  image_picker: ^0.8.6
  infinite_scroll_pagination: ^3.2.0
  package_info_plus: ^1.4.2
  pin_code_fields: ^7.4.0
  provider: ^6.0.4
  rive: ^0.9.1
  rxdart: ^0.27.4
  shared_preferences: ^2.0.15
  skeleton_text: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  timezone: ^0.9.0
  uni_links: ^0.5.1
  universal_html: ^2.0.8
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.11
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Proxima
      fonts:
        - asset: assets/fonts/ProximaNova/ProximaNova-Regular.otf
    - family: Literata
      fonts:
        - asset: assets/fonts/Literata/Literata-VariableFont.ttf
        - asset: assets/fonts/Literata/Literata-Italic-VariableFont.ttf
          style: italic
