# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Build APK for Production"
  lane :prod do
    build_number = number_of_commits()
    api_url = ENV['API_URL_PROD']
    jwt_sign_key = ENV['JWT_SIGN_KEY_PROD']
    github_workspace = ENV['GITHUB_WORKSPACE']
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--release", "--build-number=#{build_number}", "--dart-define=API_URL=#{api_url}", "--dart-define=JWT_SIGN_KEY=#{jwt_sign_key}")
    end
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
