# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do

  desc "Build and Deploy AAB for Production (Play Store)"
  lane :prod do
    api_url = ENV['API_URL']
    jwt_sign_key = ENV['JWT_SIGN_KEY']
    github_workspace = ENV['GITHUB_WORKSPACE']
    build_number = ENV['BUILD_NUMBER']
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--release", "--build-number=#{build_number}", "--dart-define=API_URL=#{api_url}", "--dart-define=JWT_SIGN_KEY=#{jwt_sign_key}")
    end
    upload_to_play_store(
      track: 'beta', 
      version_name: "500h-build-#{build_number}",
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end


  desc "Build and Deploy App for Dev-QA (Firebase Distribution)"
  lane :devqa do
    api_url = ENV['API_URL']
    jwt_sign_key = ENV['JWT_SIGN_KEY']
    build_number = ENV['BUILD_NUMBER']
    firebase_app_id = ENV['FIREBASE_ANDROID_APP_ID']
    firebase_token = ENV['FIREBASE_CLI_TOKEN']
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "apk", "--release", "--build-number=#{build_number}", "--dart-define=API_URL=#{api_url}", "--dart-define=JWT_SIGN_KEY=#{jwt_sign_key}")
    end
    firebase_app_distribution(
      app: firebase_app_id, 
      firebase_cli_token: firebase_token,
      groups: 'internal',
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      android_artifact_type: "APK"
    )
  end
end
