# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do

  desc "Build and Deploy AAB for Production (Play Store)"
  lane :test-connection-playstore do

  desc "Build and Deploy AAB for Production (Play Store)"
  lane :prod do
    api_url = ENV['API_URL']
    sar_api_url = ENV['SAR_API_URL']
    jwt_secret = ENV['JWT_SECRET']
    jwt_refresh_secret = ENV['JWT_REFRESH_SECRET']
    oidc_client_id = ENV['OIDC_CLIENT_ID']
    oidc_discover_url = ENV['OIDC_DISCOVER_URL']
    oidc_redirect_url = ENV['OIDC_REDIRECT_URI']
    build_number = ENV['BUILD_NUMBER']
    firebase_app_id = ENV['FIREBASE_ANDROID_APP_ID']
    firebase_token = ENV['FIREBASE_CLI_TOKEN']
    github_workspace = ENV['GITHUB_WORKSPACE']
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--release", 
      "--build-number=#{build_number}", 
      "--dart-define=API_URL=#{api_url}", 
      "--dart-define=SAR_API_URL=#{sar_api_url}", 
      "--dart-define=JWT_SECRET=#{jwt_secret}", 
      "--dart-define=JWT_REFRESH_SECRET=#{jwt_refresh_secret}", 
      "--dart-define=OIDC_CLIENT_ID=#{oidc_client_id}", 
      "--dart-define=OIDC_DISCOVER_URL=#{oidc_discover_url}", 
      "--dart-define=OIDC_REDIRECT_URI=#{oidc_redirect_url}", 
      "--dart-define=https=true", 
      "--dart-define=ENV=prod")
    end
    validate_play_store_json_key(
      json_key: './service_account_key.json'
    )
  end


  desc "Build and Deploy App for Dev-QA (Firebase Distribution)"
  lane :devqa do
    api_url = ENV['API_URL']
    sar_api_url = ENV['SAR_API_URL']
    jwt_secret = ENV['JWT_SECRET']
    jwt_refresh_secret = ENV['JWT_REFRESH_SECRET']
    oidc_client_id = ENV['OIDC_CLIENT_ID']
    oidc_discover_url = ENV['OIDC_DISCOVER_URL']
    oidc_redirect_url = ENV['OIDC_REDIRECT_URI']
    build_number = ENV['BUILD_NUMBER']
    firebase_app_id = ENV['FIREBASE_ANDROID_APP_ID']
    firebase_token = ENV['FIREBASE_CLI_TOKEN']
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "apk", 
        "--release", 
        "--build-number=#{build_number}", 
        "--dart-define=API_URL=#{api_url}", 
        "--dart-define=SAR_API_URL=#{sar_api_url}", 
        "--dart-define=JWT_SECRET=#{jwt_secret}", 
        "--dart-define=JWT_REFRESH_SECRET=#{jwt_refresh_secret}", 
        "--dart-define=OIDC_CLIENT_ID=#{oidc_client_id}", 
        "--dart-define=OIDC_DISCOVER_URL=#{oidc_discover_url}", 
        "--dart-define=OIDC_REDIRECT_URI=#{oidc_redirect_url}", 
        "--dart-define=ENV=qa", 
        "--dart-define=https=true", 
        "--dart-define=APP_ID_SUFFIX=.dev")
    end
    firebase_app_distribution(
      app: firebase_app_id, 
      firebase_cli_token: firebase_token,
      groups: 'qa',
      android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
      android_artifact_type: "APK"
    )
  end
end
