name: Build and Deploy Android APP (Dev-QA)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Build number
        run: |
          echo "checking count"
          count=$(git log --oneline | wc -l)
          echo "BUILD_NUMBER=$count" >> $GITHUB_ENV
          echo $count

      - name: Get Keystore Properties (Dev-QA)
        run: |
          echo '${{ secrets.ANDROID_KEY_PROPERTIES_BASE64_DEV_QA }}' > key-properties-base64.txt
          openssl base64 -d -in key-properties-base64.txt -out ${{ github.workspace }}/android/key.properties

      - name: Get Keystore jks (Dev-QA)
        run: |
          echo '${{ secrets.ANDROID_KEY_STORE_BASE64_DEV_QA }}' > keystore-base64.txt
          openssl base64 -d -in keystore-base64.txt -out ${{ github.workspace }}/android/upload-keystore.jks

      - name: Get Firebase google_services.json
        run: |
          echo '${{ secrets.ANDROID_FIREBASE_GOOGLE_SERVICES_BASE64 }}' > google_services_base64.txt
          openssl base64 -d -in google_services_base64.txt -out ${{ github.workspace }}/android/app/google-services.json

      - name: Setting Java 11
        uses: actions/setup-java@v3.5.1
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setting Flutter 3.3.4
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.4"
          channel: "stable"

      - name: Fastlane Action
        uses: maierj/fastlane-action@v2.3.0
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          API_URL: ${{ secrets.API_URL_DEV_QA }}
          JWT_SIGN_KEY: ${{ secrets.JWT_SIGN_KEY_DEV_QA }}
          BUILD_NUMBER: ${{env.BUILD_NUMBER}}
          FIREBASE_ANDROID_APP_ID: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          FIREBASE_CLI_TOKEN: ${{secrets.FIREBASE_CLI_TOKEN}}
        with:
          lane: "devqa"
          subdirectory: "android"

      # - run: flutter packages get
      # - run: flutter clean
      # - run: flutter build apk --release --build-number=${{env.BUILD_NUMBER}} --dart-define=API_URL=${{ secrets.API_URL_DEV_QA }} --dart-define=JWT_SIGN_KEY=${{ secrets.JWT_SIGN_KEY_DEV_QA }}

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: dev-qa-apk-build
      #     path: build/app/outputs/flutter-apk/app-release.apk
