name: Build and Deploy Android APP (Prod)

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Build number
        run: |
          echo "checking count"
          count=$(git log --oneline | wc -l)
          echo "BUILD_NUMBER=$count" >> $GITHUB_ENV
          echo $count

      - name: Get Keystore Properties (Prod)
        run: |
          echo '${{ secrets.ANDROID_KEY_PROPERTIES_BASE64_PROD }}' > key-properties-base64.txt
          openssl base64 -d -in key-properties-base64.txt -out ${{ github.workspace }}/android/key.properties
        # run: echo 'storePassword=${{secrets.ANDROID_STORE_PASSWORD_PROD}} keyPassword=${{secrets.ANDROID_KEY_PASSWORD_PROD}} keyAlias=${{secrets.ANDROID_KEY_ALIAS_PROD}}' > ${{ github.workspace }}/android/key.properties

      - name: Get Keystore jks (Prod)
        run: |
          echo '${{ secrets.ANDROID_KEY_STORE_BASE64_PROD }}' > keystore-base64.txt
          openssl base64 -d -in keystore-base64.txt -out ${{ github.workspace }}/android/upload-keystore.jks

      - name: Get Google Service Account (Prod)
        run: |
          echo '${{ secrets.ANDROID_GOOGLE_SERVICE_ACCOUNT_BASE64_PROD }}' > android_service_account_key_base64.txt
          openssl base64 -d -in android_service_account_key_base64.txt -out ${{ github.workspace }}/android/service_account_key.json

      - name: Get Firebase google_services.json (Prod)
        run: |
          echo '${{ secrets.ANDROID_FIREBASE_GOOGLE_SERVICES_BASE64_PROD }}' > google_services_base64.txt
          openssl base64 -d -in google_services_base64.txt -out ${{ github.workspace }}/android/app/google-services.json

      - name: Setting Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: 'android'

      - name: Setting Java 11
        uses: actions/setup-java@v3.5.1
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setting Flutter 3.13.5
        uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: "3.13.5"
          channel: "stable"

      - name: Fastlane Action
        uses: maierj/fastlane-action@v3.0.0
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          API_URL: ${{ secrets.API_URL_PROD }}
          SAR_API_URL: ${{ secrets.SAR_API_URL_PROD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET_PROD }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET_PROD }}
          OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID_PROD }}
          OIDC_DISCOVER_URL: ${{ secrets.OIDC_DISCOVER_URL_PROD }}
          OIDC_REDIRECT_URI: ${{ secrets.OIDC_REDIRECT_URI_PROD }}
          BUILD_NUMBER: ${{env.BUILD_NUMBER}}
          FIREBASE_ANDROID_APP_ID: ${{secrets.FIREBASE_ANDROID_APP_ID_PROD}}
          FIREBASE_CLI_TOKEN: ${{secrets.FIREBASE_CLI_TOKEN}}
        with:
          lane: "prod"
          subdirectory: "android"
