name: Build and Deploy Android APP

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Build number
        run: |
          echo "checking count"
          $BUILD_NUMBER = git log --oneline | wc -l
          echo $BUILD_NUMBER

      - name: Get Keystore Properties (Prod)
        run: |
          echo '${{ secrets.ANDROID_KEY_PROPERTIES_BASE64_PROD }}' > key-properties-base64.txt
          openssl base64 -d -in key-properties-base64.txt -out ${{ github.workspace }}/android/key.properties
        # run: echo 'storePassword=${{secrets.ANDROID_STORE_PASSWORD_PROD}} keyPassword=${{secrets.ANDROID_KEY_PASSWORD_PROD}} keyAlias=${{secrets.ANDROID_KEY_ALIAS_PROD}}' > ${{ github.workspace }}/android/key.properties

      - name: Get Keystore jks (Prod)
        run: |
          echo '${{ secrets.ANDROID_KEY_STORE_BASE64_PROD }}' > keystore-base64.txt
          openssl base64 -d -in keystore-base64.txt -out ${{ github.workspace }}/android/upload-keystore.jks

      - name: Get Google Service Account (Prod)
        run: |
          echo '${{ secrets.ANDROID_GOOGLE_SERVICE_ACCOUNT_BASE64_PROD }}' > android_service_account_key_base64.txt
          openssl base64 -d -in android_service_account_key_base64.txt -out ${{ github.workspace }}/android/service_account_key.json

      - name: Get Firebase google_services.json (Dev-QA)
        run: |
          echo '${{ secrets.ANDROID_FIREBASE_GOOGLE_SERVICES_BASE64_PROD }}' > google_services_base64.txt
          openssl base64 -d -in google_services_base64.txt -out ${{ github.workspace }}/android/app/google-services.json

      - name: Setting Ruby 2.7.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.2"

      - name: Setting Java 11
        uses: actions/setup-java@v3.5.1
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setting Flutter 3.3.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.3"
          channel: "stable"

      - name: Fastlane Action
        uses: maierj/fastlane-action@v2.3.0
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
          API_URL_PROD: ${{ secrets.API_URL_PROD }}
          JWT_SIGN_KEY_PROD: ${{ secrets.JWT_SIGN_KEY_PROD }}
          BUILD_NUMBER: ${{env.BUILD_NUMBER}}
        with:
          lane: "prod"
          subdirectory: "android"
