name: Build and Deploy Web APP (Prod)

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Build number
        run: |
          echo "checking count"
          count=$(git log --oneline | wc -l)
          echo "BUILD_NUMBER=$count" >> $GITHUB_ENV
          echo $count

      - name: Get dotenv file
        run: |
          echo '${{ secrets.WEB_DOTENV_BASE64 }}' > web_dotenv_base64.txt
          openssl base64 -d -in web_dotenv_base64.txt -out ${{ github.workspace }}/.env

      - name: Setting Ruby 2.7.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7.2"

      - name: Setting Java 11
        uses: actions/setup-java@v3.5.1
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setting Flutter 3.3.4
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.4"
          channel: "stable"
      - run: flutter packages get
      - run: flutter clean
      - run: flutter build web --release --build-number=${{env.BUILD_NUMBER}} --dart-define=API_URL=${{ secrets.API_URL_PROD }} --dart-define=JWT_SIGN_KEY=${{ secrets.JWT_SIGN_KEY_PROD }}

      - name: Deploying on Firebase Hosting
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install firebase-tools -g
      - run: firebase deploy -V ${{env.BUILD_NUMBER}} -m "build-${{env.BUILD_NUMBER}}" --token ${{secrets.FIREBASE_CLI_TOKEN}} -P ${{secrets.FIREBASE_PROJECT_ID}} --non-interactive
